version: '3.3'
services:
  nuxtjs:
    container_name: gachapoweb
    build: ./nuxtjs
    restart: always
    environment:
        - NODE_ENV=dev
        - HOST=0.0.0.0
        - PORT=3000
    volumes:
      - ./../user:/app
    command: /bin/sh -c "yarn && yarn dev"
    ports:
        - 3000:3000
    networks:
      - gachapo
  workspace:
    container_name: workspace
    build: ./workspace
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./../src:/www
    working_dir: /www
    # command: /bin/sh -c "npm install && npm run dev && php artisan serve"
    depends_on:
      - mysql
    networks:
      - gachapo

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - 81:80
      - 443:443
      - 8080:8080
      - 9000:9000
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - /var/logs/nginx:/var/logs/nginx
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./../src:/www
      - ./../user:/app
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - php-fpm
      - nuxtjs
    networks:
      - gachapo

  php-fpm:
    image: 'bitnami/php-fpm'
    container_name: php-fpm
    volumes:
      - ./../src:/www
      - ./php-fpm/conf.d/app.ini:/opt/bitnami/php/etc/conf.d/app.ini
    restart: always
    networks:
      - gachapo

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'gachapo'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3308:3306
    expose:
      - 3306
    volumes:
      - ~/.gachapo/mysql:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - /var/logs/mysql:/var/logs/mysql
    networks:
      - gachapo

networks:
  gachapo:

volumes:
  gachapo:
